spring:
  # 热重启
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/templates?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      # 初始化时建立物理连接数的个数
      initialSize : 5
      # 最大连接池的个数
      maxActive: 20
      # 最小连接池的个数
      minIdle: 5
      # 获取连接时的最大等待时间，单位为毫秒
      maxWait: 60000
      # 配置间隔多久才进行以一次检测，检测时需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      # 用来检测是否是是有效的 sql，要求是一个查询语句
      validationQuery: SELECT 1 FROM DUAL
      # 申请连接时检测，如果有空闲时间大于 timeBetweenEvictionRunsMillis 执行 validationQuery 检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行 validationQuery 检测连接是否有效，该配置会降低性能
      testOnBorrow: false
      # 归还连接时执行 validationQuery 检测连接是否有效，该配置会降低性能
      testOnReturn: false
      # 是否缓存 preparedStatement，也就是 PSCache。PSCache 对支持游标的数据库性能提升巨大，比如说 oracle。在 mysql 下建议关闭。
      poolPreparedStatements: true
      # 要启用 PSCache，必须配置大于 0，当大于 0 时，poolPreparedStatements 自动触发修改为 true。
      maxPoolPreparedStatementPerConnectionSize: 50
      # 配置监控统计拦截的 filters，去掉后监控界面 sql 无法统计.
      # stat: 监控统计  log4j: 日志记录  wall: 防御 sql 注入
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个 DruidDataSource 的监控数据
      useGlobalDataSourceStat: true


# 应用服务 WEB 访问端口
server:
  port: 8080

# mybatis 的配置
mybatis:
  # 搜索指定包别名
#  typeAliasesPackage: com.gzw.**.domain
  # mybatis 配置文件的位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 映射文件的位置
  mapper-locations: classpath:mapper/**/*Mapper.xml
